set['ganglia']['http_port']              = "80"
set['ganglia']['sysadmin_email']         = "root@localhost"
set['ganglia']['docroot']                = "/usr/share/ganglia-webfrontend"
set['ganglia']['conf_dir']               = "/etc/ganglia-webfrontend"
set['ganglia']['log_dir']                = "/var/log/ganglia"
set['ganglia']['user']                   = "www-data"
set['ganglia']['group']                  = "www-data"

default['ganglia']['server_auth_method'] = "openid"
default['ganglia']['version']            = "3.1.7"
default['ganglia']['uri']                = "http://sourceforge.net/projects/ganglia/files/ganglia%20monitoring%20core/3.1.7/ganglia-3.1.7.tar.gz/download"
default['ganglia']['checksum']           = "bb1a4953"
default['ganglia']['cluster_name']       = "default"
default['ganglia']['unicast']            = false
default['ganglia']['server_role']        = "monitoring"
